# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-26 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myresepies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resepi',
            name='created_by',
            field=models.CharField(default='user', max_length=30),
        ),
    ]
